version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=store-app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=store-app-db
    ports:
      - '5432:5432'