// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"
	product "stabulum/internal/domain/product"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0, _a1
func (_m *Repository) Add(_a0 context.Context, _a1 product.Product) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, product.Product) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
